[package]
name = "flutter_rust_bridge_example"
version = "1.0.0"
edition = "2018"

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.52", features = ["backtrace"] }
flutter_rust_bridge = { path = "../../../frb_rust" }
lazy_static = "1.4.0"
