name: Publish

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  rust_codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo publish --verbose
        working-directory: ./frb_codegen
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  rust_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo publish --verbose
        working-directory: ./frb_rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  rust_macros:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo publish --verbose
        working-directory: ./frb_macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  dart_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          package_directory: frb_dart
          credential: ${{ secrets.PUB_CREDENTIALS_JSON }}
          flutter_package: false
          skip_test: true
